CREATE DATABASE airline_reservation;
USE airline_reservation;

CREATE TABLE FLIGHT (
    FlightID VARCHAR(20) PRIMARY KEY,
    DepartureTime DATETIME NOT NULL,
    ArrivalTime DATETIME NOT NULL,
    Source VARCHAR(50) NOT NULL,
    Destination VARCHAR(50) NOT NULL,
    AvailableClass ENUM('ECONOMY', 'BUSINESS', 'FIRST') NOT NULL,
    TotalSeats INT NOT NULL,
    AvailableSeats INT NOT NULL,
    Status ENUM('ON_TIME', 'DELAYED', 'CANCELLED', 'BOARDING', 'DEPARTED', 'LANDED') NOT NULL
);


CREATE TABLE PASSENGER (
    PassengerID INT  PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Phone VARCHAR(20) NOT NULL,
    SeatPreference ENUM('WINDOW', 'AISLE', 'NO_PREFERENCE') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SEAT (
    SeatID VARCHAR(20) PRIMARY KEY,
    FlightID VARCHAR(20),
    SeatNumber VARCHAR(10) NOT NULL,
    SeatClass ENUM('ECONOMY', 'BUSINESS', 'FIRST') NOT NULL,
    Status ENUM('AVAILABLE', 'BOOKED', 'BLOCKED') NOT NULL,
    Position ENUM('WINDOW', 'MIDDLE', 'AISLE') NOT NULL,
    FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID)
);

CREATE TABLE BOOKING (
    BookingID VARCHAR(20) PRIMARY KEY,
    PassengerID INT ,
    FlightID VARCHAR(20),
    SeatID VARCHAR(20),
    BookingDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    Status ENUM('CONFIRMED', 'CANCELLED', 'PENDING') NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    PaymentStatus ENUM('PAID', 'PENDING', 'REFUNDED') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (PassengerID) REFERENCES PASSENGER(PassengerID),
    FOREIGN KEY (FlightID) REFERENCES FLIGHT(FlightID),
    FOREIGN KEY (SeatID) REFERENCES SEAT(SeatID)
);

CREATE TABLE LOYALTY_PROGRAM (
    ProgramID VARCHAR(20) PRIMARY KEY,
    PassengerID INT,
    MilesAccumulated INT DEFAULT 0,
    PointsBalance INT DEFAULT 0,
    PointsRedeemed INT DEFAULT 0,
    MembershipTier ENUM('BASIC', 'SILVER', 'GOLD', 'PLATINUM') NOT NULL,
    JoinDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    LastActivityDate DATETIME,
    FOREIGN KEY (PassengerID) REFERENCES PASSENGER(PassengerID)
);